"""New designation made

Revision ID: 475eb8633d73
Revises: 2d8d90210fcb
Create Date: 2023-11-10 00:15:47.848947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475eb8633d73'
down_revision = '2d8d90210fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
